---
abstract: 'A POE abstraction layer for conciseness and simplicity'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.80
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: POE::Declare
name: POE-Declare
no_index:
  directory:
    - inc
    - t
requires:
  Class::ISA: 0.33
  Class::Inspector: 1.22
  Class::XSAccessor: 0.14
  IO::File: 1.14
  List::Util: 1.18
  POE: 1.003
  Params::Util: 0.38
  Scalar::Util: 1.18
  perl: 5.8.7
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
