---
abstract: 'A POE abstraction layer for conciseness and simplicity'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.27
  Test::More: 0.80
  Test::NoWarnings: 0.084
  Test::POE::Stopping: 1.05
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: POE::Declare
name: POE-Declare
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::ISA: 0.33
  Class::Inspector: 1.22
  Class::XSAccessor: 1.05
  IO::File: 1.14
  List::Util: 1.19
  POE: 1.293
  Params::Util: 1.00
  Scalar::Util: 1.19
  perl: 5.8.7
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/POE-Declare
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/POE-Declare
version: 0.50
